### ISSUE TITLE
Support Catherine BMD & BF scripts

### ISSUE THREAD

**Issue by tge-was-taken** [tge-was-taken/Atlus-Script-Tools#1]

**Comment by jihnwock** [comment]
Hi, is this issue still planned to be handled ?
Since the release of Catherine Full Body, I've been looking for a way to adapt your code in order to read `.bmd` and `.bf` files.
My attempt haven't come to fruition since the headers of the file seem to have drastically changed (so I guess the `ASM` did too) and I don't find a way to analyze them properly.
I'd love to contribute to the project so if you have any kind of lead I could start with it would be a pleasure for me to follow it and report my progress here.
Thanks.

**Comment by Shasties** [comment]
Bumping this request since specifically for Catherine Classic it would be useful.

**Comment by tge-was-taken** [comment]
Fixed by 7dc067a35f49dd543110b1b6661b40e1df2393f0
